version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=POSTGRES
      - POSTGRES_DB=POSTGRES
